# 1. Base stage for shared settings
FROM node:24-alpine AS base
WORKDIR /app
# Install libc6-compat for sharp and Next.js SWC, plus build tools in case native modules need compilation
RUN apk add --no-cache libc6-compat python3 make g++
ENV NEXT_TELEMETRY_DISABLED 1

# 2. Dependencies stage to cache node_modules
FROM base AS deps
COPY package.json package-lock.json* npm-shrinkwrap.json* yarn.lock* pnpm-lock.yaml* ./
RUN \
    if [ -f package-lock.json ]; then npm ci --legacy-peer-deps || npm install --legacy-peer-deps; \
    elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
    else npm install --legacy-peer-deps; \
    fi

# 3. Development stage for hot-reloading (used by docker-compose)
FROM base AS development
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Start development server
CMD ["npm", "run", "dev"]

# 4. Builder stage to compile the application
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Build the Next.js app (using standalone output generated by next.config.ts)
RUN npm run build

# 5. Production runtime stage
FROM base AS production
ENV NODE_ENV production

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy static files and public assets
COPY --from=builder /app/public ./public
# Set proper permissions for prerender cache
RUN mkdir .next && chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# server.js is created by next build from the standalone output
CMD ["node", "server.js"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 CMD node -e "fetch('http://127.0.0.1:' + (process.env.PORT || 3000) + '/api/health').then((response) => { if (!response.ok) process.exit(1) }).catch(() => process.exit(1))"
