'use client'

import Image, { type ImageProps } from 'next/image'

type CmsImageProps = Omit<ImageProps, 'src' | 'alt'> & {
    src: string
    alt: string
}

export default function CmsImage({ src, alt, ...props }: CmsImageProps) {
    let normalizedSrc = src

    if (/^https?:\/\//.test(src)) {
        try {
            const parsedUrl = new URL(src)

            // Media generated by Payload in local development should stay on the current origin
            // so the app still works when Next falls back to another localhost port.
            if (parsedUrl.hostname === 'localhost' || parsedUrl.hostname === '127.0.0.1') {
                normalizedSrc = `${parsedUrl.pathname}${parsedUrl.search}`
            }
        } catch {
            normalizedSrc = src
        }
    }

    const isRemote = /^https?:\/\//.test(normalizedSrc)

    // Dynamically check production server URL and default domains
    const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL
    let serverHostname = 'cr-culture.com'
    if (serverUrl) {
        try {
            serverHostname = new URL(serverUrl).hostname
        } catch {}
    }

    const isKnownOptimizedHost = new RegExp(
        `localhost|127\\.0\\.0\\.1|crculture\\.go\\.th|cr-culture\\.com|${serverHostname.replace(/\./g, '\\.')}`
    ).test(normalizedSrc)

    return (
        <Image
            src={normalizedSrc}
            alt={alt}
            unoptimized={isRemote && !isKnownOptimizedHost}
            {...props}
        />
    )
}